DELETE http://localhost:3003/api/blogs/67ee87c95fe9811686f7984f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmFhbmRlcnNvbiIsImlkIjoiNjdmM2RkMDk5ZDhkNmI0MGE0YTZhNzdkIiwiaWF0IjoxNzQ0MDM1MjMyLCJleHAiOjE3NDQwMzg4MzJ9.8_at27EiHJW2yfQDOtOIgIMtX6-IfS99szdIMTpxggk
